spring:
  application:
    name: "GewerbeService"
  banner:
    location: classpath:/Banner.txt

cxf:
  path: /soap-api

server:
  forward-headers-strategy: native

biproadapter:
  provider:
    common:
      genericstandardadapter:
        mtom: true
        checksum: true
        wsdl:
           location: "classpath:/wsdl/GewerbeService_2.7.1.1.0.wsdl"
        xslt:
           xmlcleanup: true
           file: responseCleanUpTransformation.xsl
        bipro:
          version: "2.7.1.1.0"
        authentication:
          required: false
        cryption:
          jks:
            enabled: no
        signature:
          jks:
            enabled: no
        authorisation:
          domain: NORM426
          enabled: false
          url: "t.b.d."
    norm420common:
      product:
        norm420commonstandardadapter:
          supported:
            processes:
              signature:
                - "00"
              payment:
                - "1"
                - "2"
    norm426:
      product:
        norm426standardadapter:
          endpoint:
            servicename: "GewerbeService_2.7.1.1.0"

management:
  endpoint:
    metrics:
      enabled: true

  endpoints:
    web:
      exposure:
        include: info,health

logging:
  # Change to "development-logback-spring.xml" or start with -Dlogging.config="classpath:development-logback-spring.xml" to use simple logging instead of json output
  # You can provide your own logback-spring.xml and place it in this folder. Adjust this parameter for activation.
  config: "classpath:default-logback-spring.xml"
  level:
    eu.fincon.biproadapter: INFO
